
try {
    throw "Some serious error";
} catch (error) {
    console.error(error);
}

// throw - serves to throw error